
_HANDLER_TYPE_COMMAND_ = "commandHandler"
_HANDLER_TYPE_MESSAGE_ = "messageHandler"
_HANDLER_TYPE_ERROR_ = "errorHandler"

_MENU_DATA_COMMAND_OPTION = "command"
_MENU_DATA_URL_OPTION = "url"
_CALLBACK_QUERY_COMMAND_OPTION = "command"
_CALLBACK_QUERY_ARGS_OPTION = "args"

_MESSAGE_HANDLER_TEXT_ = "mhText"
_MESSAGE_HANDLER_IMAGE_ = "mhImage"

_BOT_HELP_COMMAND_ = "help"
