
_HANDLER_TYPE_COMMAND_ = "commandHandler"
_HANDLER_TYPE_MESSAGE_ = "messageHandler"
_HANDLER_TYPE_ERROR_ = "errorHandler"
_HANDLER_TYPE_FUNCTION_ = "functionHandler"
_HANDLER_TYPE_CALLBACK_ = "callBackHandler"

_MENU_DATA_COMMAND_OPTION = "command"
_MENU_DATA_URL_OPTION = "url"
_MENU_DATA_FUNCTION_OPTION = "function"
_CALLBACK_QUERY_COMMAND_OPTION = _MENU_DATA_COMMAND_OPTION
_CALLBACK_QUERY_FUNCTION_OPTION = _MENU_DATA_FUNCTION_OPTION
_CALLBACK_QUERY_ARGS_OPTION = "args"

_MESSAGE_HANDLER_TEXT_ = "mhText"
_MESSAGE_HANDLER_IMAGE_ = "mhImage"

_BOT_HELP_COMMAND_ = "help"


_MESSAGE_INDEX_ = 0
_MENU_INDEX_ = 1