
_DF_ = "/"

_OUTPUT_BOT_NAME_ = "bot.py"
_OUTPUT_BOT_DIR_ = "bot"
_MODULES_DIR_ = "modules"
_MODULES_EXTENTION_ = "py"
_CONFIG_FILE_NAME_ = "ravegen.conf"
_CONFIG_DIR_NAME_ = "config"
_CONFIG_FILE_PATH = _CONFIG_DIR_NAME_ + _DF_ + _CONFIG_FILE_NAME_
OUTPUT_BOT_PATH = _OUTPUT_BOT_DIR_ +  _DF_ + _OUTPUT_BOT_NAME_


_TEMP_LS_MODULES_FILE_NAME = ".tempModuels"


_CONFIG_RAVEGEN_SECTION_ = "RaveGen"
_CONFIG_HOSTING_OPTION_ = "hosting"
_CONFIG_TOKEN_OPTION_ = "token"
_CONFIG_PROJECT_NAME_OPTION_ = "project_name"


_LINUX_MKDIR_COMMAND_ = "mkdir "
_LINUX_LS_COMMAND_ = "ls "
_LINUX_RM_COMMAND_ = "rm -f "
_LINUX_RM_COMMAND_DIR = "rm -Rf "
_LINUX_WRITE_COMMAND_ = " > "



_CRITICAL_ERROR_ = 1
_NORMAL_ERROR_ = 2


