
_DF_ = "/"
_DD_ = ":"

_ACTUAL_PATH = "./"
_HTTPS_ = "https://"


_PYC_EXTENTION = ".pyc"
_GIT_EXTENTION = ".git"

_STR_TRUE_ = "True"

_OUTPUT_BOT_NAME_ = "bot.py"
_OUTPUT_BOT_DIR_ = "bot"
_MODULES_DIR_ = "modules"
_MODULES_EXTENTION_ = "py"
_LOG_DIR_NAME_ = "log"
_LOG_FILE_NAME_ = "log"
_LOG_FILE_PATH_ = _LOG_DIR_NAME_ + _DF_ + _LOG_FILE_NAME_
_CONFIG_FILE_NAME_ = "ravegen.conf"
_CONFIG_DIR_NAME_ = "config"
_CONFIG_FILE_PATH = _CONFIG_DIR_NAME_ + _DF_ + _CONFIG_FILE_NAME_
OUTPUT_BOT_PATH = _OUTPUT_BOT_DIR_ +  _DF_ + _OUTPUT_BOT_NAME_


#CONSOLE ENGINE CONSTANTS
_CONSOLE_ENGINE_INFO_OPTION_ = "Info"
_CONSOLE_ENGINE_OPTION_TAG_ = "Options"


_TEMP_LS_MODULES_FILE_NAME = ".tempModuels"
_TEMP_LS_VERIFY_FILE_NAME = ".tempVerifyFiles"


_CONFIG_RAVEGEN_SECTION_ = "RaveGen"
_CONFIG_HOSTING_OPTION_ = "hosting"
_CONFIG_TOKEN_OPTION_ = "token"
_CONFIG_DEPLOY_URL_OPTION = "deploy_url"
_CONFIG_DEPLOY_PORT_OPRION = "deploy_port"
_CONFIG_WEBHOOK_PATH_OPTION = "webhook_path"
_CONFIG_PROJECT_NAME_OPTION_ = "project_name"
_CONFIG_GIT_OPTION_ = "git"
_CONFIG_VERBOSE_OPTION_ = "verbose"
_CONFIG_LOG_OPTION_ = "log"

_INIT_CONFIG_TOKEN_ = "__TOKEN__"
_INIT_CONFIG_DEPLOY_URL = "__URL__"
_INIT_CONFIG_DEPLOY_PORT = "__PORT__"
_INIT_CONFIG_WEBHOOK_PATH = "__PATH__"
_INIT_CONFIG_VERBOSE = "yes"
_INIT_CONFIG_LOG = "yes"
_INIT_CONFIG_PROJECT_NAME = "__PROJECT__NAME__"

_HEADER_TOKEN_FLAG = "TokenFlag"


_DEPLOY_HEROKU_OPTION = "heroku"


_HEROKU_URL = ".herokuapp.com/"
_HEORKU_GIT_URL = "git.heroku.com/"


_LINUX_MKDIR_COMMAND_ = "mkdir -p "
_LINUX_LS_COMMAND_ = "ls "
_LINUX_RM_COMMAND_ = "rm -f "
_LINUX_RM_COMMAND_DIR = "rm -Rf "
_LINUX_WRITE_COMMAND_ = " > "
_LINUX_PYTHON_COMMAND_ = "python "
_LINUX_ALL_TAG_ = "*"
_LINUX_HEROKU_COMMAND_ = "heroku "
_LINUX_HEROKU_CREATE_OPTION_ = "create "


_CRITICAL_ERROR_ = 1
_NORMAL_ERROR_ = 2


